### ISSUE TITLE
Any samples?

### ISSUE THREAD

**Issue by tan90xx** [hrnoh24/stream-vc#2]
Hi@hrnoh24, I've trained your streamvc on LJSpeech dataset. Until now, maybe something wrong (with epoch=14 ).
Can you provide more detailed information? e.g. the output or checkpoint from model you trained.

Thanks
![image](https://github.com/hrnoh24/stream-vc/assets/44235744/99c29140-172a-4b63-a2ad-c81e0046cd45)

**Comment by hrnoh24** [comment]
Hi @tan90xx 

Thank you for your interest in this repository.

Unfortunately, this repository is still a work in progress and cannot be trained on yet.

Did you take a separate model and train it? I would appreciate it if you could tell me in more detail how you trained it.

Thanks

**Comment by tan90xx** [comment]
Of course~
